services:
  blocky-ui:
    image: ghcr.io/gabeduartem/blocky-ui:latest
    container_name: blocky-ui
    restart: unless-stopped
    depends_on:
      - blocky
    ports:
      - 3000:3000
    volumes:
      - ./logs.csv:/logs.csv
    environment:
      - BLOCKY_API_URL=http://localhost:3001
      - QUERY_LOG_TYPE=csv
      - QUERY_LOG_TARGET=/logs.csv
      - INSTANCE_NAME=blocky-raspi5

  blocky:
    image: spx01/blocky
    container_name: blocky
    hostname: blocky
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
      - ./logs.csv:/logs.csv
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4000:3001
      - 54:53/udp
